<?php
return [
    'components'=>[
        'JUREN_12_1_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3332;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_1_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_1_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_2_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3334;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_2_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_2_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_3_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3336;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_3_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_3_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_4_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_4_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_4_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_5_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_5_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_5_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_6_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3338;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_6_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_6_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_7_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_7_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_7_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_8_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3330;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_8_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_8_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_9_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3334;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_9_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_9_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_10_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3336;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_10_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'JUREN_12_10_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
    ]
];