<?php
return [
    'components'=>[
        'LSTX_5_1_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3310;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_1_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_1_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_2_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_2_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_2_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_3_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_3_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_3_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_4_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_4_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_4_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_5_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_5_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_5_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_6_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_6_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_6_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_7_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_7_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_7_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_8_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_8_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_8_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_9_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3326;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_9_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_9_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_10_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_10_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_10_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_11_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3330;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_11_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_11_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_12_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3332;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_12_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_12_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],

        'LSTX_5_13_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_13_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_13_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],

        'LSTX_5_14_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_14_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'LSTX_5_14_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
    ]
];