<?php
return [
    'components' => [
        'MRZG_8_1_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3310;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_1_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_1_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_2_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_2_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_2_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_3_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_3_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_3_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_4_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_4_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_4_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_5_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_5_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_5_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_6_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_6_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'MRZG_8_6_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
    ],
];
