<?php
return [
    'components' => [
        'TZCQ_9_1_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3310;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_1_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_1_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3326;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3330;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_12_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3332;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_12_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_12_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_13_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_13_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_13_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_14_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_14_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_14_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_15_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_15_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_15_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_16_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_16_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_16_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_17_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3334;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_17_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_17_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_18_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_18_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_18_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_19_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3326;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_19_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_19_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_20_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_20_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_20_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_21_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3332;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_21_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_21_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_22_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3336;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_22_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_22_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_23_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_23_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_23_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_24_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_24_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_24_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_25_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_25_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_25_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_26_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_26_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_26_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_27_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3330;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_27_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_27_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_28_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_28_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_28_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_29_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_29_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_29_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_30_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_30_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_30_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_31_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3336;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_31_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_31_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_32_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3338;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_32_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_32_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_33_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_33_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_33_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_34_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_34_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_34_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_35_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3340;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_35_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3341;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_35_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3341;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_36_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_36_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_36_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_37_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_37_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_37_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_38_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_38_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_38_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_39_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3332;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_39_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_39_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3333;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_40_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3334;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_40_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_40_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3335;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_41_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3336;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_41_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_41_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3337;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_42_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3338;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_42_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_42_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3339;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_43_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3342;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_43_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3343;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_43_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3343;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_44_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3344;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_44_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3345;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_44_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3345;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_45_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_45_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_45_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_46_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_46_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_46_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_47_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_47_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_47_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
    ],
];
