<?php
return [
    'components' => [
        'TZCQ_9_1_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3310;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_1_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_1_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3311;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3312;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_2_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3313;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3314;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_3_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3315;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3316;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_4_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3317;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3318;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_5_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3319;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3320;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3321;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_6_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3322;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_7_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3323;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3324;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_8_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3325;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3326;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_9_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3327;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3328;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_10_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3329;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_octgame' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3330;dbname=octgame',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_ocenter' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=ocenter',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
        'TZCQ_9_11_octlog' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost:3331;dbname=octlog',
            'username' => 'root',
            'password' => '123456',
            //'charset' => 'utf8_general_ci',
        ],
    ],
];
