<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-04-19
 * Time: 15:51
 */

namespace api\controllers;

use api\models\TabItemAdd;
use Yii;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class ItemaddController extends ActiveController
{
    public $modelClass="api\models\TabItemAdd";
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];
    public function actions()
    {
        $actions= parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['delete'],$actions['create'],$actions['update'],$actions['index']);
        return $actions;
    }
    public function actionIndex($sku,$serverId,$db,$playerName,$itemId,$src,$identId,$from,$to)
    {
//        exit(var_dump(Yii::$app->request->getQueryParams()));
        TabItemAdd::setDBPrefix($sku,$serverId,$db);
        $query=TabItemAdd::find();
        //必要字段
        $query->where(['playername'=>$playerName,'gameId'=>$sku])
        ->andFilterWhere([//非必要字段
            'mIdentId'=>$identId,
            'src'=>$src,
            'mTypeID'=>$itemId,
        ])
        ->andFilterWhere(['>=','logtime',$from])
        ->andFilterWhere(['<=','logtime',$to]);
        $data=new ActiveDataProvider([
            'query'=>$query,
        ]);
//        exit($query->createCommand()->getRawSql());
        return $data;
    }
}