<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-04-24
 * Time: 11:47
 */

namespace api\controllers;

use api\models\TabItemRem;
use Yii;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class ItemremController extends ActiveController
{
    public $modelClass="api\models\TabItemRem";
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];
    public function actions()
    {
        $actions= parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['delete'],$actions['create'],$actions['update'],$actions['index']);
        return $actions;
    }
    public function actionIndex($sku,$did,$serverId,$db,$playerName,$itemId,$src,$identId,$from,$to)
    {
//        exit(var_dump(Yii::$app->request->getQueryParams()));
        TabItemRem::setDBPrefix($sku,$did,$serverId,$db);
        $query=TabItemRem::find();
        //必要字段
        $query->where(['playername'=>$playerName])
            ->andFilterWhere([//非必要字段
                'mIdentId'=>$identId,
                'src'=>$src,
                'mTypeID'=>$itemId,
            ])
            ->andFilterWhere(['>=','logtime',$from])
            ->andFilterWhere(['<=','logtime',$to]);
        $data=new ActiveDataProvider([
            'query'=>$query,
        ]);
//        exit($query->createCommand()->getRawSql());
        return $data;
    }
}