<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-05-07
 * Time: 16:21
 */

namespace api\controllers;

use api\models\LoginInfo;
use api\models\LoginValidate;
use yii\rest\ActiveController;

/**
 * Class LoginController
 * 玩家登录验证,步骤：
 * 1.参数验证
 * 2.sign验证
 * 3.保存登录信息，已有则刷新登录时间跟ticket;
 * 4.记录登录日志信息
 * 5.防沉迷校验
 * @package api\controllers
 */
class LoginController extends ActiveController
{
    public $modelClass="api\models\LoginInfo";

    public function actions()
    {
        $actions= parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['delete'],$actions['create']);

        return $actions;
    }
    public function actionCreate()
    {

        $request=\Yii::$app->request;

        $searchModel=new LoginValidate();
        $searchModel->load($request->queryParams);
        if($searchModel->validate())
        {
            $haveOne=LoginInfo::find()->where(['username'=>$searchModel->username])->one();
            if ($haveOne===null)
            {

            }else{
                $searchModel->save();
            }
        }else{
//            $response=\Yii::$app->response();
        }
    }
}