<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-04-24
 * Time: 11:08
 */

namespace api\controllers;

use api\models\TabTradevc;
use yii\rest\ActiveController;
use yii\data\ActiveDataProvider;

class TradevcController extends ActiveController
{
    public $modelClass="api\models\TabTradevc";

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];
    public function actions()
    {
        $actions= parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['delete'],$actions['create'],$actions['update'],$actions['index']);
        return $actions;
    }
    public function actionIndex($sku,$did,$serverId,$db,$playerName,$targetName,$vcoin,$from,$to)
    {
        TabTradevc::setDBPrefix($sku,$did,$serverId,$db);
        $query=TabTradevc::find();

        $query->andFilterWhere(['tradeG'=>$playerName])
            ->andFilterWhere(['tradeM'=>$targetName])
            ->andFilterWhere(['<=','logtime',$to])
            ->andFilterWhere(['>=','logtime',$from])
            ->andFilterWhere(['>=','vcoin',$vcoin]);

        $data=new ActiveDataProvider([
            'query'=>$query,
        ]);
//        exit($query->createCommand()->getRawSql());
        return $data;
    }
}