<?php
/**
 * Created by PhpStorm.
 * User: lipenghui
 * Date: 2019-05-07
 * Time: 16:30
 */

namespace api\models;


class LoginValidate extends LoginInfo
{
    public $isAdult;
    public $sign;
    public function rules()
    {
//         parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['serverid','username','channelId','onlineip','Logintime','deviceId','sign'],'required'],
            [['sign'],'string'],
            [['onlineip'], 'string', 'max' => 50],
            [['channelId'], 'string', 'max' => 45],
            [['username', 'serverid', 'ticket', 'source', 'deviceId'], 'string', 'max' => 255],
        ];
    }
}